### PR TITLE
RPI4 compatibility, CMake improvements, Github CI, Performance Improvements

### PR DESCRIPTION
**Pull request by rob-ack**
Intended for review and discussion ground to:
- modernize cmake outdating the old make scripts.
- build rpi4 compatibility
- improving Performance (i.e. scsp got improved by around 18% by introducing better thread synchronization)
- introducing new Github CI scripts since travis does not actually run anymore.
- compile fixes for MSVC, CLang removing the need of complicated MinGW, MSYS Toolchains to support Windows Builds
- Adds CMake support to build LibRetro libs under Windows and Linux (Tested with RetroArch Win10 and rpi4)
- ... more to come

### CODE REVIEW

**Comment by dankcushions** [comment]
https://github.com/libretro/yabause/blob/2eae70987d6b2f53b73d55c23b34acf12bafc0fe/Retropie/installscript/lr-kronos/lr-kronos-rob-ack.sh

this should be added to retropie, not the core. libretro cores shouldn't care about retropie but you can certainly make a PR for retropie when the support is completed :)

**Comment by rob-ack** [comment]
> https://github.com/libretro/yabause/blob/2eae70987d6b2f53b73d55c23b34acf12bafc0fe/Retropie/installscript/lr-kronos/lr-kronos-rob-ack.sh
> 
> this should be added to retropie, not the core. libretro cores shouldn't care about retropie but you can certainly make a PR for retropie when the support is completed :)

Yes. For now this is just included here to give devs an already working script to get the repo running in retropie via source build by adding it manually.
It needs additional changes like the real repo url when the final repo and branch is even known finally. And the support for rpi4 in kronos has to be finished (basically OpenGlES instruction complexity reduction to prevent Mesa from crashing) before starting real work of adding the script to retropie.

**Comment by barbudreadmon** [comment]
This is an upstreamed core, all changes must go through https://github.com/FCare/Kronos first

**Comment by barbudreadmon** [comment]
Also, i highly recommend splitting this in several PRs, in its current state your PR is barely readable.

**Comment by barbudreadmon** [comment]
@rob-ack I briefly discussed this PR with @FCare, he thinks some of your changes will be ok and some others will be dangerous and/or will break things, so again i highly recommend splitting this in smaller PRs before sending them upstream to discuss the changes individually. It might also help to [join us on discord](https://discordapp.com/invite/c5q4EU2)

**Pull request closed without merging**
