### PR TITLE
[WIP] [Needs testing] Rebase against upstream

### PR DESCRIPTION
**Pull request by rtissera**
Rebase on upstream, many emulation improvements :
    - SH2 cache emulation
    - SCU jobs improvements
    - (Not enabled yet) Vulkan renderer
    - A few SH2 dynarec fixes

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Sounds exciting!

**Comment by Ntemis** [comment]
@barbudreadmon compiles and runs fine on my tests

**Comment by barbudreadmon** [comment]
failing everywhere : https://git.libretro.com/libretro/yabasanshiro/-/pipelines/138819

**Comment by rtissera** [comment]
This is a WIP draft which was not meant to be merged.
Notably compute shaders should be adjusted to #version 310 es
Looking into CI build issues to fix them.

Le mar. 27 sept. 2022 à 21:45, barbudreadmon ***@***.***> a
écrit :

**Comment by barbudreadmon** [comment]
>This is a WIP draft which was not meant to be merged.

@rtissera I was pinged from multiple sources the same day by people that were supposedly related to you from working on some kind of retrogaming distro (i forgot the name), asking me to merge this. Hence why i merged this.
 
It won't happen again, in the first i didn't want to deal with this core anymore with upstream not respecting yabause license. From now on, you'll have to reach out @LibretroAdmin if you want anything merged to this branch.

**Comment by rtissera** [comment]
@barbudreadmon no problem. Will ping @LibretroAdmin when ready and tested.
This is a big changeset, uplifting requirements to GLES 3.1, switching to compute shaders (same way as Kronos works), so this needs to be discussed (pros and cons).

**Comment by LibretroAdmin** [comment]
Hi @rtissera , contact BoardsOfCanada on Discord and we can discuss further. Thanks.

**Comment by Kelvfimer** [comment]
@barbudreadmon Any chance of having @rtissera on this pr again? The emulator is stuck in the past

**Pull request merged**
